// SPDX-License-Identifier: UNLICENSED
// Auto-generated by @phase-mirror/multiplicity-native-proof
// Circuit : consent (1.0.0)
// Generated: 2026-03-21
// DO NOT EDIT MANUALLY — regenerate with: node scripts/generate-native-verifier.mjs

pragma solidity ^0.8.20;

interface IMultiplicityVerifier {
    function verifyNativeProof(
        bytes32 piNative,
        bytes32 commitment,
        bytes32[] calldata publicSignals
    ) external view returns (bool);
}

/**
 * @title NativeVerifier_consent
 * @notice Verifies native-multiplicity proofs for the "consent" circuit (1.0.0).
 * @dev Proof encoding mirrors TypeScript prover.ts — sha256(abi.encodePacked(...)).
 *      Public signals must be supplied in the canonical order:
 *        [0] purpose_id
 *        [1] scope_hash
 *        [2] provider_pk
 *        [3] patient_pk
 *        [4] expiry_epoch
 *        [5] now_epoch
 *        [6] delta_bound
 *        [7] consent_commitment
 *        [8] server_time
 *        [9] nullifier
 */
contract NativeVerifier_consent is IMultiplicityVerifier {
    uint256 public constant PUBLIC_SIGNAL_COUNT = 10;

    bytes32 public constant CIRCUIT_ID =
        sha256(abi.encodePacked("consent:1.0.0"));

    function verifyNativeProof(
        bytes32 piNative,
        bytes32 commitment,
        bytes32[] calldata publicSignals
    ) external pure override returns (bool) {
        require(
            publicSignals.length == PUBLIC_SIGNAL_COUNT,
            "NativeVerifier_consent: wrong signal count"
        );

        // Recompute piNative = sha256(circuitId ∥ sig[0] ∥ … ∥ sig[n])
        bytes32 expectedPiNative = sha256(
            abi.encodePacked(CIRCUIT_ID, publicSignals[0], publicSignals[1], publicSignals[2], publicSignals[3], publicSignals[4], publicSignals[5], publicSignals[6], publicSignals[7], publicSignals[8], publicSignals[9])
        );
        if (piNative != expectedPiNative) return false;

        // Recompute commitment = sha256("commit:" ∥ piNative)
        bytes32 expectedCommitment = sha256(
            abi.encodePacked("commit:", piNative)
        );
        return commitment == expectedCommitment;
    }
}
