// SPDX-License-Identifier: UNLICENSED
// Auto-generated by @phase-mirror/multiplicity-native-proof
// Circuit : research_consent (1.0.0)
// Generated: 2026-03-21
// DO NOT EDIT MANUALLY — regenerate with: node scripts/generate-native-verifier.mjs

pragma solidity ^0.8.20;

interface IMultiplicityVerifier {
    function verifyNativeProof(
        bytes32 piNative,
        bytes32 commitment,
        bytes32[] calldata publicSignals
    ) external view returns (bool);
}

/**
 * @title NativeVerifier_research_consent
 * @notice Verifies native-multiplicity proofs for the "research_consent" circuit (1.0.0).
 * @dev Proof encoding mirrors TypeScript prover.ts — sha256(abi.encodePacked(...)).
 *      Public signals must be supplied in the canonical order:
 *        [0] study_id
 *        [1] anonymity_budget_hash
 *        [2] research_commitment
 *        [3] donation_nullifier
 */
contract NativeVerifier_research_consent is IMultiplicityVerifier {
    uint256 public constant PUBLIC_SIGNAL_COUNT = 4;

    bytes32 public constant CIRCUIT_ID =
        sha256(abi.encodePacked("research_consent:1.0.0"));

    function verifyNativeProof(
        bytes32 piNative,
        bytes32 commitment,
        bytes32[] calldata publicSignals
    ) external pure override returns (bool) {
        require(
            publicSignals.length == PUBLIC_SIGNAL_COUNT,
            "NativeVerifier_research_consent: wrong signal count"
        );

        // Recompute piNative = sha256(circuitId ∥ sig[0] ∥ … ∥ sig[n])
        bytes32 expectedPiNative = sha256(
            abi.encodePacked(CIRCUIT_ID, publicSignals[0], publicSignals[1], publicSignals[2], publicSignals[3])
        );
        if (piNative != expectedPiNative) return false;

        // Recompute commitment = sha256("commit:" ∥ piNative)
        bytes32 expectedCommitment = sha256(
            abi.encodePacked("commit:", piNative)
        );
        return commitment == expectedCommitment;
    }
}
